Run('cmd.exe')
        Sleep(1000)
        send('TCTX64_20210701\TCTX64_20210701.exe{ENTER}')
        send('{ENTER}')
        Sleep(500)
        send('T')
        send('FE')
send('sup2{ENTER}')
send('a')
send('sup2{ENTER}')
send('y')
        send('{ENTER}')
        send('{ENTER}')
        send('x')
        send('x')
        send('exit{ENTER}')
        