Run('cmd.exe')
        Sleep(500)
        send('cd TCTX64_20210701{ENTER}')
        send('TCTX64_20210701.exe{ENTER}')
        Sleep(100)
        send('{ENTER}')
        Sleep(100)
        send('T')
        Sleep(100)
        send('CE')
        Sleep(1000)
send('sup{ENTER}')
        send('{ENTER}')
        send('y')
        send('{ENTER}')
        Sleep(0)
        send('x')
        send('x')
        send('exit{ENTER}')
        